apiVersion: v1
kind: ServiceAccount
metadata:
  name: nudl
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nudl
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nudl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nudl
subjects:
  - kind: ServiceAccount
    name: nudl
    namespace: default
---
kind: DaemonSet
apiVersion: apps/v1
metadata: 
  name: nudl
  labels:
    app.kubernetes.io/name: nudl
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nudl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nudl
    spec:
      serviceAccountName: nudl
      containers:
      - name: nudl
        image: leonnicolas/nudl
        args: 
        - --hostname=$(NODE_NAME)
        - --no-contain=usb,hub
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http
          containerPort: 8080
