name: ci

on:
  push:
    branches: main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker build -t "nudl:e2e" .

  multi_arch:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - id: sha
        run: echo "sha=$(git describe --always --tags --dirty)" >> "$GITHUB_OUTPUT"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64, linux/arm, linux/amd64
          tags: |
            leonnicolas/nudl:latest
            leonnicolas/nudl:${{ steps.sha.outputs.sha }}
            ghcr.io/leonnicolas/nudl:latest
            ghcr.io/leonnicolas/nudl:${{ steps.sha.outputs.sha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
