name: test

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install libusb-1.0-0-dev -y
      - run: docker build -t "nudl:e2e" .
      - run: go test .
